# Generated by Django 3.2.3 on 2021-05-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('file_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('file_address', models.CharField(max_length=225)),
                ('user_id', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('hashtag', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'file_info',
                'managed': False,
            },
        ),
    ]
