# Generated by Django 3.2.3 on 2021-05-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f4hashtag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('s3_address', models.CharField(max_length=225)),
                ('user_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('hashtag', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'file',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='FileInfo',
        ),
    ]
